### ISSUE TITLE
Hi all, where "visualization" in model.py of mapalign project?

### ISSUE THREAD

**Issue by khoatranrb** [Lydorn/netsimilarity#2]

**Comment by Lydorn** [comment]
@khoatranrb Hi, I am sorry but I do not not understand your question... Can you explain more?

**Comment by khoatranrb** [comment]
> @khoatranrb Hi, I am sorry but I do not not understand your question... Can you explain more?

In https://github.com/Lydorn/netsimilarity/blob/master/projects/mapalign/mapalign_multires/model.py, line 16, I dont know where  "visualization" is it. I think you missed some files while uploading to github.

**Comment by Lydorn** [comment]
Oh right, sorry about that! I've added the missing file as well as another one that is needed in model.py.
